### ISSUE TITLE
Administrateur > Agents ne fonctionne plus sans ADE

### ISSUE THREAD

**Issue by vinriviere** [EsupPortail/esup-emargement#22]
Je viens de mettre à jour mon environnement de pré-production avec Esup-emargement 1.1.1. Le menu "Administrateur > Agents" ne fonctionne plus, ça provoque une erreur technique.

Une erreur est survenue

Erreur
    Internal Server Error
Message
Trace
    java.net.ConnectException: Connexion refusée (Connection refused) at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) at java.base/
...
at org.esupportail.emargement.services.AdeService.getSessionId(AdeService.java:681) at org.esupportail.emargement.services.AdeService$$FastClassBySpringCGLIB$$8c52afc8.invoke(<generated>) at 

Je précise que je n'utilise pas ADE, et que dans les configurations ADE_ENABLED est à false.

En revanche, les autres menus fonctionnent correctement.

**Comment by jptran** [comment]
Corrigé dans le commit du 25/11/2024

**Comment by vinriviere** [comment]
Merci @jptran, ça marche.
